---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ww
  labels:
    app: ww
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ww
  template:
    metadata:
      labels:
        app: ww
    spec:
      containers:
        - name: ww
          image: docker.io/phengbunath/ww:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
